#!/usr/bin/env python3
"""Corrige les accents manquants dans les articles blog-pro et blog."""
import re
from pathlib import Path

# Dictionnaire de corrections — mot sans accent → mot avec accent
# Format : (regex_pattern, replacement)
# On remplace uniquement dans le texte visible (entre balises), pas dans les URLs/attributs
CORRECTIONS = [
    # ─── é ───
    (r'\bdecennale\b', 'décennale'),
    (r'\bDecennale\b', 'Décennale'),
    (r'\BDECENNALE\b', 'DÉCENNALE'),
    (r'\benergetique\b', 'énergétique'),
    (r'\bEnergetique\b', 'Énergétique'),
    (r'\belectricite\b', 'électricité'),
    (r'\bElectricite\b', 'Électricité'),
    (r'\belectricien\b', 'électricien'),
    (r'\bElectricien\b', 'Électricien'),
    (r'\belectriciens\b', 'électriciens'),
    (r'\bElectriciens\b', 'Électriciens'),
    (r'\belectrique\b', 'électrique'),
    (r'\bElectrique\b', 'Électrique'),
    (r'\belectriques\b', 'électriques'),
    (r'\brenovation\b', 'rénovation'),
    (r'\bRenovation\b', 'Rénovation'),
    (r'\brenover\b', 'rénover'),
    (r'\bRenover\b', 'Rénover'),
    (r'\brenovent\b', 'rénovent'),
    (r'\brenovez\b', 'rénovez'),
    (r'\brenovons\b', 'rénovons'),
    (r'\brenovation\b', 'rénovation'),
    (r'\breglement\b', 'règlement'),
    (r'\bReglementation\b', 'Réglementation'),
    (r'\breglementation\b', 'réglementation'),
    (r'\breglementer\b', 'réglementer'),
    (r'\belegible\b', 'éligible'),
    (r'\beligible\b', 'éligible'),
    (r'\bEligible\b', 'Éligible'),
    (r'\beligibles\b', 'éligibles'),
    (r'\bEligibles\b', 'Éligibles'),
    (r'\benergie\b', 'énergie'),
    (r'\bEnergie\b', 'Énergie'),
    (r'\benergies\b', 'énergies'),
    (r'\beconomie\b', 'économie'),
    (r'\bEconomie\b', 'Économie'),
    (r'\beconomies\b', 'économies'),
    (r'\beconomiser\b', 'économiser'),
    (r'\bequipement\b', 'équipement'),
    (r'\bEquipement\b', 'Équipement'),
    (r'\bequipements\b', 'équipements'),
    (r'\betape\b', 'étape'),
    (r'\betapes\b', 'étapes'),
    (r'\bEtape\b', 'Étape'),
    (r'\belement\b', 'élément'),
    (r'\bElement\b', 'Élément'),
    (r'\belements\b', 'éléments'),
    (r'\belabore\b', 'élaboré'),
    (r'\belaborer\b', 'élaborer'),
    (r'\bevaluation\b', 'évaluation'),
    (r'\bevaluer\b', 'évaluer'),
    (r'\bevalue\b', 'évalué'),
    (r'\betudie\b', 'étudié'),
    (r'\betudie\b', 'étudié'),
    (r'\betude\b', 'étude'),
    (r'\betudes\b', 'études'),
    (r'\bEtude\b', 'Étude'),
    (r'\bEtudes\b', 'Études'),
    (r'\bepargne\b', 'épargne'),
    (r'\bevolution\b', 'évolution'),
    (r'\bEvolution\b', 'Évolution'),
    (r'\beviter\b', 'éviter'),
    (r'\bevite\b', 'évité'),
    # ─── è ───
    (r'\bprobleme\b', 'problème'),
    (r'\bProbleme\b', 'Problème'),
    (r'\bproblemes\b', 'problèmes'),
    (r'\bsysteme\b', 'système'),
    (r'\bSysteme\b', 'Système'),
    (r'\bsystemes\b', 'systèmes'),
    (r'\bcritere\b', 'critère'),
    (r'\bCritere\b', 'Critère'),
    (r'\bcriteres\b', 'critères'),
    (r'\bmatiere\b', 'matière'),
    (r'\bMatieres\b', 'Matières'),
    (r'\bmatières\b', 'matières'),
    (r'\bcomplete\b', 'complète'),
    (r'\bComplete\b', 'Complète'),
    (r'\bcomplets\b', 'complets'),
    (r'\bregulier\b', 'régulier'),
    (r'\breguliere\b', 'régulière'),
    (r'\bregulierement\b', 'régulièrement'),
    (r'\breguliers\b', 'réguliers'),
    (r'\bpiege\b', 'piège'),
    (r'\bPiege\b', 'Piège'),
    (r'\bpieges\b', 'pièges'),
    (r'\bPieges\b', 'Pièges'),
    (r'\bfenetres?\b', 'fenêtres'),
    (r'\bFenetres?\b', 'Fenêtres'),
    (r'\bmodele\b', 'modèle'),
    (r'\bModele\b', 'Modèle'),
    (r'\bmodeles\b', 'modèles'),
    (r'\bconsequence\b', 'conséquence'),
    (r'\bconsequences\b', 'conséquences'),
    (r'\bexperience\b', 'expérience'),
    (r'\bExpérience\b', 'Expérience'),
    (r'\bexperiences\b', 'expériences'),
    (r'\bpresence\b', 'présence'),
    (r'\bPrésence\b', 'Présence'),
    (r'\breference\b', 'référence'),
    (r'\bReferences\b', 'Références'),
    (r'\breferences\b', 'références'),
    (r'\bpreference\b', 'préférence'),
    (r'\bpreferences\b', 'préférences'),
    (r'\bprocedure\b', 'procédure'),
    (r'\bprocedures\b', 'procédures'),
    # ─── ê ───
    (r'\bbatiment\b', 'bâtiment'),
    (r'\bBatiment\b', 'Bâtiment'),
    (r'\bbatiments\b', 'bâtiments'),
    (r'\bBatiments\b', 'Bâtiments'),
    # ─── é (suite) ───
    (r'\bdefaut\b', 'défaut'),
    (r'\bDefaut\b', 'Défaut'),
    (r'\bpenalite\b', 'pénalité'),
    (r'\bpenalites\b', 'pénalités'),
    (r'\bPenalites\b', 'Pénalités'),
    (r'\bmetier\b', 'métier'),
    (r'\bMetier\b', 'Métier'),
    (r'\bmetiers\b', 'métiers'),
    (r'\bMetiers\b', 'Métiers'),
    (r'\bsecurite\b', 'sécurité'),
    (r'\bSecurite\b', 'Sécurité'),
    (r'\breel\b', 'réel'),
    (r'\bReel\b', 'Réel'),
    (r'\breels\b', 'réels'),
    (r'\breelle\b', 'réelle'),
    (r'\breelles\b', 'réelles'),
    (r'\bverifier\b', 'vérifier'),
    (r'\bverifiez\b', 'vérifiez'),
    (r'\bverifie\b', 'vérifié'),
    (r'\bvérifié\b', 'vérifié'),
    (r'\bverification\b', 'vérification'),
    (r'\bverifications\b', 'vérifications'),
    (r'\bpresenter\b', 'présenter'),
    (r'\bpresente\b', 'présente'),
    (r'\bpresentes\b', 'présentées'),
    (r'\bprevenir\b', 'prévenir'),
    (r'\bprevention\b', 'prévention'),
    (r'\bPreventions\b', 'Préventions'),
    (r'\bprevenir\b', 'prévenir'),
    (r'\bprevoir\b', 'prévoir'),
    (r'\bprevoyez\b', 'prévoyez'),
    (r'\bproteger\b', 'protéger'),
    (r'\bprotege\b', 'protégé'),
    (r'\bprotegez\b', 'protégez'),
    (r'\bpropriete\b', 'propriété'),
    (r'\bPropriete\b', 'Propriété'),
    (r'\bproprietes\b', 'propriétés'),
    (r'\bpropriétaires\b', 'propriétaires'),
    (r'\bpropriétaire\b', 'propriétaire'),
    (r'\bredressement\b', 'redressement'),
    (r'\bredresse\b', 'redressé'),
    (r'\bregulier\b', 'régulier'),
    (r'\bdedie\b', 'dédié'),
    (r'\bdediees\b', 'dédiées'),
    (r'\bdebutant\b', 'débutant'),
    (r'\bDeclaration\b', 'Déclaration'),
    (r'\bdeclaration\b', 'déclaration'),
    (r'\bdeclarations\b', 'déclarations'),
    (r'\bdeclarer\b', 'déclarer'),
    (r'\bdepassement\b', 'dépassement'),
    (r'\bdepassements\b', 'dépassements'),
    (r'\bdelai\b', 'délai'),
    (r'\bDelai\b', 'Délai'),
    (r'\bdelais\b', 'délais'),
    (r'\bDélais\b', 'Délais'),
    (r'\bdemarche\b', 'démarche'),
    (r'\bDemarche\b', 'Démarche'),
    (r'\bdemarches\b', 'démarches'),
    (r'\bDemarches\b', 'Démarches'),
    (r'\bdedommagement\b', 'dédommagement'),
    (r'\bdedommager\b', 'dédommager'),
    (r'\bdeduction\b', 'déduction'),
    (r'\bdeductible\b', 'déductible'),
    (r'\bdeductibles\b', 'déductibles'),
    (r'\bagrement\b', 'agrément'),
    (r'\bAgrément\b', 'Agrément'),
    (r'\bagréments\b', 'agréments'),
    (r'\bameliorer\b', 'améliorer'),
    (r'\bamelioration\b', 'amélioration'),
    (r'\bAmelioration\b', 'Amélioration'),
    (r'\bameliorations\b', 'améliorations'),
    (r'\bamenagement\b', 'aménagement'),
    (r'\bAmenagement\b', 'Aménagement'),
    (r'\bamenagements\b', 'aménagements'),
    (r'\bgenerale\b', 'générale'),
    (r'\bgeneralement\b', 'généralement'),
    (r'\bgeneral\b', 'général'),
    (r'\bGeneral\b', 'Général'),
    (r'\bgenerer\b', 'générer'),
    (r'\bgenere\b', 'généré'),
    (r'\bvéritablement\b', 'véritablement'),
    (r'\bveritable\b', 'véritable'),
    (r'\bveritablement\b', 'véritablement'),
    (r'\bveritables\b', 'véritables'),
    (r'\bcertifie\b', 'certifié'),
    (r'\bcertifiee\b', 'certifiée'),
    (r'\bcertification\b', 'certification'),
    (r'\bcertifications\b', 'certifications'),
    (r'\bqualifie\b', 'qualifié'),
    (r'\bQualifie\b', 'Qualifié'),
    (r'\bqualifies\b', 'qualifiés'),
    (r'\bqualifiee\b', 'qualifiée'),
    (r'\bqualifiees\b', 'qualifiées'),
    (r'\bspecifique\b', 'spécifique'),
    (r'\bspecifiques\b', 'spécifiques'),
    (r'\bspecialise\b', 'spécialisé'),
    (r'\bspecialisee\b', 'spécialisée'),
    (r'\bspecialistes\b', 'spécialistes'),
    (r'\bspecialiste\b', 'spécialiste'),
    (r'\bspecialite\b', 'spécialité'),
    (r'\bspecialites\b', 'spécialités'),
    # ─── à/â ───
    (r'\bsupreme\b', 'suprême'),
    (r'\bmeme\b', 'même'),
    (r'\bMeme\b', 'Même'),
    (r'\bsystematique\b', 'systématique'),
    (r'\bsystematiquement\b', 'systématiquement'),
    # ─── ç ───
    (r'\bcedille\b', 'cédille'),
    # ─── Mots techniques BTP fréquents ───
    (r'\bmaçonnerie\b', 'maçonnerie'),
    (r'\bmaconnerie\b', 'maçonnerie'),
    (r'\bMaçonnerie\b', 'Maçonnerie'),
    (r'\bMaconnerie\b', 'Maçonnerie'),
    (r'\bsous-traitance\b', 'sous-traitance'),
    (r'\bindemnisation\b', 'indemnisation'),
    (r'\bindemnisations\b', 'indemnisations'),
    (r'\bindemniser\b', 'indemniser'),
    (r'\bresponsabilite\b', 'responsabilité'),
    (r'\bResponsabilite\b', 'Responsabilité'),
    (r'\bresponsabilites\b', 'responsabilités'),
    (r'\bgarantie\b', 'garantie'),
    (r'\bgaranties\b', 'garanties'),
    (r'\bobligatoire\b', 'obligatoire'),
    (r'\bobligatoires\b', 'obligatoires'),
    (r'\boperation\b', 'opération'),
    (r'\boperations\b', 'opérations'),
    (r'\bObligations\b', 'Obligations'),
    (r'\bobligations\b', 'obligations'),
    (r'\bverification\b', 'vérification'),
    (r'\bverifications\b', 'vérifications'),
    (r'\bprestataire\b', 'prestataire'),
    (r'\bprestataires\b', 'prestataires'),
    (r'\brealite\b', 'réalité'),
    (r'\bRealite\b', 'Réalité'),
    (r'\brealiser\b', 'réaliser'),
    (r'\brealise\b', 'réalisé'),
    (r'\brealisez\b', 'réalisez'),
    (r'\brealisee\b', 'réalisée'),
    (r'\brealisees\b', 'réalisées'),
    (r'\bdevis\b', 'devis'),  # already correct
    (r'\bfacturee\b', 'facturée'),
    (r'\bfacturees\b', 'facturées'),
    (r'\bfacture\b(?!s\b)', 'facture'),  # careful with "factures" (noun)
    (r'\bsalarie\b', 'salarié'),
    (r'\bsalaries\b', 'salariés'),
    (r'\bsalariee\b', 'salariée'),
    (r'\bconcrete\b', 'concrète'),
    (r'\bconcretes\b', 'concrètes'),
    (r'\bconcretement\b', 'concrètement'),
    (r'\bConcretement\b', 'Concrètement'),
]

def fix_text_in_html(html, corrections):
    """Applique les corrections uniquement dans le texte entre balises (pas dans les attributs/URLs)."""
    result = []
    # Split sur les balises pour traiter uniquement le texte
    parts = re.split(r'(<[^>]+>)', html)
    for part in parts:
        if part.startswith('<'):
            # Balise HTML — ne pas modifier
            result.append(part)
        else:
            # Texte visible — appliquer les corrections
            for pattern, replacement in corrections:
                part = re.sub(pattern, replacement, part)
            result.append(part)
    return ''.join(result)

dirs = [
    Path("/Users/moctar/Desktop/batispot-site/blog-pro"),
    Path("/Users/moctar/Desktop/batispot-site/blog"),
]

total_fixed = 0
total_replacements = 0

for d in dirs:
    for f in sorted(d.glob("*.html")):
        if f.name.startswith('_'):
            continue
        original = f.read_text(encoding="utf-8")
        fixed = fix_text_in_html(original, CORRECTIONS)
        if fixed != original:
            # Compte les changements
            changes = sum(1 for a, b in zip(original, fixed) if a != b)
            f.write_text(fixed, encoding="utf-8")
            total_fixed += 1
            total_replacements += changes

print(f"✅ Articles corrigés : {total_fixed}")
print(f"✅ Caractères modifiés : {total_replacements:,}")